name: groups
version: '1.0-SNAPSHOT'

main: org.nig.smp.groups.Groups
api-version: '1.21.11'
load: POSTWORLD

softdepend:
  - LuckPerms
  - PlaceholderAPI

commands:
  donate:
    description: "Управление донатами"
    usage: "/donate [сумма]"
    aliases: [donate, don, дон]
  donations:
    description: "Управление донатами (админка)"
    usage: "/donations [reload]"
    aliases: [donationsadmin, дон]
    permission: donate.admin

permissions:
  donate.admin:
    description: "Доступ к админ-командам донатов"
    default: op
  donate.starter:
    description: "Уровень доната Starter"
    default: false
  donate.premium:
    description: "Уровень доната Premium"
    default: false
  donate.vip:
    description: "Уровень доната VIP"
    default: false
  donate.elite:
    description: "Уровень доната ELITE"
    default: false
  donate.sponsor:
    description: "Уровень доната SPONSOR"
    default: false
