# Шанс выпадения головы (0.0 - 1.0)
drop-chance: 1.0

# Выпадение головы при смерти от другого игрока (PvP)
pvp: true

# Выпадение головы при смерти от мобов (PvE)
pve: false

# Выпадение головы при смерти от других причин (падение, утопление и т.д.)
other: false
