#include "app.h"

Bitmap* g_original = nullptr;
Bitmap* g_gray = nullptr;
std::wstring g_originalPath;
std::wstring g_resultPath;
std::wstring g_status;
bool g_statusOk = false;

float g_mmW = 100.0f;
float g_mmH = 100.0f;
float g_dpi = 100.0f;
float g_feed = 600.0f;
float g_power = 70.0f;

// Fit the grayscale image to the fixed engraving canvas (mm x DPI -> pixels).
// Top-left aligned so GRBL always burns from the same origin.
Bitmap* FitToLaser(Bitmap* src)
{
    if (!src) return nullptr;
    float iw = (float)src->GetWidth();
    float ih = (float)src->GetHeight();
    if (iw <= 0 || ih <= 0) return nullptr;

    int canvasW = (int)(g_mmW * g_dpi / 25.4f + 0.5f);
    int canvasH = (int)(g_mmH * g_dpi / 25.4f + 0.5f);
    if (canvasW < 1) canvasW = 1;
    if (canvasH < 1) canvasH = 1;

    float scale = std::min((float)canvasW / iw, (float)canvasH / ih);
    int w = (int)(iw * scale + 0.5f);
    int h = (int)(ih * scale + 0.5f);
    if (w < 1) w = 1;
    if (h < 1) h = 1;

    Bitmap* out = new Bitmap(canvasW, canvasH, PixelFormat32bppARGB);
    Graphics g(out);
    g.Clear(Color::White);
    g.SetInterpolationMode(InterpolationModeHighQualityBicubic);
    g.DrawImage(src, 0, 0, w, h);
    return out;
}

static std::wstring GcodePathFor(const std::wstring& pngPath)
{
    std::wstring p = pngPath;
    size_t dot = p.find_last_of(L'.');
    if (dot != std::wstring::npos) p = p.substr(0, dot);
    return p + L".nc";
}

// Re-apply current engraving settings to the existing result.
void ApplyLaserSettings()
{
    if (!g_gray) return;
    Bitmap* fitted = FitToLaser(g_gray);
    if (!fitted) return;
    delete g_gray;
    g_gray = fitted;

    std::wstring ncPath = GcodePathFor(g_resultPath);
    bool pngOk = SaveBitmap(g_gray, g_resultPath);
    bool ncOk = GenerateGCode(g_gray, ncPath, g_feed, g_power, g_dpi);

    if (pngOk && ncOk)
    {
        g_status = L"Готово — " + g_resultPath + L" (" +
                   std::to_wstring(fitted->GetWidth()) + L"×" +
                   std::to_wstring(fitted->GetHeight()) + L" px) + " + ncPath;
        g_statusOk = true;
    }
    else if (pngOk)
    {
        g_status = L"Ошибка G-code: " + ncPath;
        g_statusOk = false;
    }
    else
    {
        g_status = L"Ошибка сохранения: " + g_resultPath;
        g_statusOk = false;
    }
    UpdateButtonStates();
    InvalidateRect(g_hwnd, NULL, TRUE);
}

// Generate raster G-code for GRBL (M3 laser on / S power per pixel row).
// Scans top-to-bottom, serpentine to minimize travel. Step = 25.4/dpi mm.
bool GenerateGCode(Bitmap* bmp, const std::wstring& path, float feed, float powerPct, float dpi)
{
    if (!bmp) return false;
    UINT w = bmp->GetWidth();
    UINT h = bmp->GetHeight();
    if (w == 0 || h == 0) return false;

    std::vector<BYTE> lum(w * h);
    {
        BitmapData data;
        Rect rc(0, 0, (int)w, (int)h);
        if (bmp->LockBits(&rc, ImageLockModeRead, PixelFormat32bppARGB, &data) != Ok)
            return false;
        for (UINT y = 0; y < h; y++)
        {
            const BYTE* row = (const BYTE*)data.Scan0 + (INT)y * data.Stride;
            for (UINT x = 0; x < w; x++)
            {
                const BYTE* p = row + x * 4;
                lum[y * w + x] = (BYTE)((30 * p[2] + 59 * p[1] + 11 * p[0]) / 100);
            }
        }
        bmp->UnlockBits(&data);
    }

    float stepMm = 25.4f / dpi;          // mm per pixel
    float maxS = 1000.0f * (powerPct / 100.0f); // GRBL S range 0..1000
    if (maxS < 0) maxS = 0;
    if (maxS > 1000) maxS = 1000;

    std::wstring gcode;
    gcode.reserve(w * h * 14);
    gcode += L"; Generated by PhotoToBW\r\n";
    gcode += L"; size " + std::to_wstring(w) + L" x " + std::to_wstring(h) +
             L" px, step " + std::to_wstring(stepMm) + L" mm\r\n";
    gcode += L"G21 G90 G17\r\n";
    gcode += L"F" + std::to_wstring((int)feed) + L"\r\n";
    gcode += L"G0 X0 Y0\r\n";
    gcode += L"M5\r\n";

    for (UINT y = 0; y < h; y++)
    {
        float yy = y * stepMm;
        bool leftToRight = (y % 2 == 0);
        gcode += L"G0 Y" + std::to_wstring(yy) + L"\r\n";

        // emit row as runs of equal S to keep the file small
        UINT x = 0;
        while (x < w)
        {
            UINT xi = leftToRight ? x : (w - 1 - x);
            BYTE l = lum[y * w + xi];
            float s = maxS * (1.0f - l / 255.0f);   // black = burn
            if (s < 0) s = 0;
            if (s > maxS) s = maxS;
            UINT start = x;
            while (x < w)
            {
                UINT xj = leftToRight ? x : (w - 1 - x);
                BYTE lj = lum[y * w + xj];
                float sj = maxS * (1.0f - lj / 255.0f);
                if (sj < 0) sj = 0;
                if (sj > maxS) sj = maxS;
                if (std::abs(sj - s) > 2.0f) break;
                x++;
            }
            UINT endX = leftToRight ? (x - 1) : (w - x);
            gcode += L"G1 X" + std::to_wstring((float)endX * stepMm) +
                     L" S" + std::to_wstring((int)s) + L"\r\n";
        }
    }

    gcode += L"M5\r\nG0 X0 Y0\r\n";

    HANDLE hFile = CreateFileW(path.c_str(), GENERIC_WRITE, 0, NULL,
                               CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (hFile == INVALID_HANDLE_VALUE) return false;
    DWORD written = 0;
    // write as UTF-8
    int wlen = (int)gcode.size();
    int blen = WideCharToMultiByte(CP_UTF8, 0, gcode.c_str(), wlen, NULL, 0, NULL, NULL);
    std::vector<char> buf(blen);
    WideCharToMultiByte(CP_UTF8, 0, gcode.c_str(), wlen, buf.data(), blen, NULL, NULL);
    WriteFile(hFile, buf.data(), (DWORD)blen, &written, NULL);
    CloseHandle(hFile);
    return true;
}

static int GetEncoderClsid(const WCHAR* mime, CLSID* pClsid)
{
    UINT num = 0, size = 0;
    GetImageEncodersSize(&num, &size);
    if (size == 0) return -1;
    ImageCodecInfo* info = (ImageCodecInfo*)malloc(size);
    if (!info) return -1;
    GetImageEncoders(num, size, info);
    for (UINT i = 0; i < num; i++)
    {
        if (wcscmp(info[i].MimeType, mime) == 0)
        {
            *pClsid = info[i].Clsid;
            free(info);
            return (int)i;
        }
    }
    free(info);
    return -1;
}

Bitmap* MakeGrayscale(Bitmap* src)
{
    if (!src) return nullptr;
    UINT w = src->GetWidth();
    UINT h = src->GetHeight();
    Bitmap* dst = new Bitmap(w, h, PixelFormat32bppARGB);
    Graphics g(dst);
    ColorMatrix cm;
    memset(&cm, 0, sizeof(cm));
    cm.m[0][0] = 0.299f; cm.m[0][1] = 0.299f; cm.m[0][2] = 0.299f;
    cm.m[1][0] = 0.587f; cm.m[1][1] = 0.587f; cm.m[1][2] = 0.587f;
    cm.m[2][0] = 0.114f; cm.m[2][1] = 0.114f; cm.m[2][2] = 0.114f;
    cm.m[3][3] = 1.0f;
    cm.m[4][4] = 1.0f;
    ImageAttributes attrs;
    attrs.SetColorMatrix(&cm);
    g.DrawImage(src, Rect(0, 0, (int)w, (int)h), 0, 0, (int)w, (int)h, UnitPixel, &attrs);
    return dst;
}

static std::wstring MakeOutputPath(const std::wstring& srcPath)
{
    size_t slash = srcPath.find_last_of(L"\\/");
    size_t dot = srcPath.find_last_of(L'.');
    std::wstring dir = (slash == std::wstring::npos) ? L"" : srcPath.substr(0, slash + 1);
    std::wstring name;
    std::wstring ext = L".png";
    if (dot != std::wstring::npos && dot > slash)
    {
        name = srcPath.substr(slash + 1, dot - slash - 1);
        ext = srcPath.substr(dot);
    }
    else
    {
        name = srcPath.substr(slash + 1);
    }
    std::wstring lower = ext;
    for (auto& c : lower) c = towlower((wint_t)c);
    std::wstring outExt = L".png";
    if (lower == L".jpg" || lower == L".jpeg" || lower == L".bmp" ||
        lower == L".gif" || lower == L".tif" || lower == L".tiff" || lower == L".png")
        outExt = lower;
    return dir + name + L"_bw" + outExt;
}

static const WCHAR* MimeForPath(const std::wstring& path)
{
    std::wstring lower = path;
    for (auto& c : lower) c = towlower((wint_t)c);
    if (lower.find(L".jpg") != std::wstring::npos || lower.find(L".jpeg") != std::wstring::npos)
        return L"image/jpeg";
    if (lower.find(L".bmp") != std::wstring::npos) return L"image/bmp";
    if (lower.find(L".gif") != std::wstring::npos) return L"image/gif";
    if (lower.find(L".tif") != std::wstring::npos || lower.find(L".tiff") != std::wstring::npos)
        return L"image/tiff";
    return L"image/png";
}

bool SaveBitmap(Bitmap* bmp, const std::wstring& path)
{
    CLSID clsid;
    if (GetEncoderClsid(MimeForPath(path), &clsid) == -1) return false;
    return bmp->Save(path.c_str(), &clsid, NULL) == Ok;
}

void UpdateButtonStates()
{
    bool has = (g_gray != nullptr);
    GetBtn(kBtnSaveAs)->enabled = has;
    GetBtn(kBtnClear)->enabled = has;
}

bool ProcessFile(const std::wstring& path)
{
    Bitmap* src = Bitmap::FromFile(path.c_str());
    if (!src || src->GetLastStatus() != Ok)
    {
        if (src) delete src;
        g_status = L"Не удалось открыть: " + path;
        g_statusOk = false;
        InvalidateRect(g_hwnd, NULL, TRUE);
        return false;
    }
    Bitmap* gray = MakeGrayscale(src);
    Bitmap* fitted = FitToLaser(gray);
    delete gray;
    gray = fitted;

    delete g_original;
    delete g_gray;
    g_original = src;
    g_gray = gray;
    g_originalPath = path;
    g_resultPath = MakeOutputPath(path);

    if (SaveBitmap(gray, g_resultPath) &&
        GenerateGCode(gray, GcodePathFor(g_resultPath), g_feed, g_power, g_dpi))
    {
        g_status = L"Готово — " + g_resultPath + L" (" +
                   std::to_wstring(gray->GetWidth()) + L"×" +
                   std::to_wstring(gray->GetHeight()) + L" px) + " +
                   GcodePathFor(g_resultPath);
        g_statusOk = true;
    }
    else
    {
        g_status = L"Ошибка сохранения: " + g_resultPath;
        g_statusOk = false;
    }

    UpdateButtonStates();
    InvalidateRect(g_hwnd, NULL, TRUE);
    return true;
}

void OpenFileDialog()
{
    wchar_t file[MAX_PATH] = L"";
    OPENFILENAMEW ofn = {};
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner = g_hwnd;
    ofn.lpstrFilter = L"Изображения\0*.jpg;*.jpeg;*.png;*.bmp;*.gif;*.tif;*.tiff\0Все файлы\0*.*\0";
    ofn.lpstrFile = file;
    ofn.nMaxFile = MAX_PATH;
    ofn.Flags = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST;
    if (GetOpenFileNameW(&ofn))
        ProcessFile(ofn.lpstrFile);
}

void SaveAsDialog()
{
    if (!g_gray || g_resultPath.empty()) return;
    wchar_t file[MAX_PATH] = L"";
    wcscpy_s(file, g_resultPath.c_str());
    OPENFILENAMEW ofn = {};
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner = g_hwnd;
    ofn.lpstrFilter = L"PNG (*.png)\0*.png\0JPEG (*.jpg)\0*.jpg\0BMP (*.bmp)\0*.bmp\0GIF (*.gif)\0*.gif\0TIFF (*.tiff)\0*.tiff\0";
    ofn.lpstrFile = file;
    ofn.nMaxFile = MAX_PATH;
    ofn.lpstrDefExt = L"png";
    ofn.Flags = OFN_OVERWRITEPROMPT;
    if (GetSaveFileNameW(&ofn))
    {
        if (SaveBitmap(g_gray, ofn.lpstrFile))
        {
            g_status = L"Сохранено — " + std::wstring(ofn.lpstrFile);
            g_statusOk = true;
        }
        else
        {
            g_status = L"Ошибка сохранения";
            g_statusOk = false;
        }
        InvalidateRect(g_hwnd, NULL, TRUE);
    }
}

void ClearAll()
{
    delete g_original; g_original = nullptr;
    delete g_gray; g_gray = nullptr;
    g_originalPath.clear();
    g_resultPath.clear();
    g_status.clear();
    UpdateButtonStates();
    InvalidateRect(g_hwnd, NULL, TRUE);
}

void DoAction(int id)
{
    switch (id)
    {
    case kBtnOpen: OpenFileDialog(); break;
    case kBtnSaveAs: SaveAsDialog(); break;
    case kBtnClear: ClearAll(); break;
    }
}
